name: Run Aviron Monitors

on:
  schedule:
    # 1st & 15th of each month at 14:00 UTC (~biweekly)
    - cron: "0 14 1,15 * *"
  workflow_dispatch:  # lets you run it manually

permissions:
  contents: write   # allows committing updated history files

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitors
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
          DEFAULT_CURRENCY: USD
          NORMALIZE_REGEX: '[^0-9\.]'
          STRIP_UTM: "1"
          MIN_PRICE_FLOOR: "400"
          NEWS_LOOKBACK_DAYS: "14"
        run: python run_all.py

      - name: Commit updated history files
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add history.json news_history.json || true
          git diff --staged --quiet || git commit -m "Update histories [skip ci]"
          git push
